version: "3.1"

services:
  database:
    image: timescale/timescaledb:latest-pg11
    restart: always
    ports: 
      - 5431:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: acqdat_prod
    volumes: 
      - pgdata:/var/lib/postgresql/data
  
  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    restart: always
    container_name: es01
    environment: 
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - esdata:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200

  web:
    build: 
      context: ../../
      dockerfile: ./devops/local/Dockerfile
    restart: always
    container_name: web
    ports:
      - 4001:4001
      - 4000:4000
    environment:
      APP_IOT_PORT: ${APP_IOT_PORT}
      APP_API_PORT: ${APP_API_PORT}
      APP_HOSTNAME: ${APP_HOSTNAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      SENDGRID_KEY: ${SENDGRID_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      GUARDIAN_API_KEY: ${GUARDIAN_API_KEY}
      GUARDIAN_IOT_KEY: ${GUARDIAN_IOT_KEY}
      ELASTIC_SEARCH_HOST: ${ELASTIC_SEARCH_HOST}
    depends_on:
      - database
      - elastic_search
  
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./data/nginx/conf.d/:/etc/nginx/conf.d/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on: 
      - web
  
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes: 
  esdata:
  pgdata:
