version: "3.1"

services:
  database:
    image: timescale/timescaledb:latest-pg11
    restart: always
    ports: 
      - 5431:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: acqdat_prod
    volumes: 
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    ports: 
      - 5601:5601
    environment: 
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200

  mqtt_broker:
    build:
      context: ../../
      dockerfile: ./devops/local/mqtt/Dockerfile
      args:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
    restart: always
    ports:
      - 1882:1883
    volumes:
      - vernemqdata:/vernemq/data
      - vernemqlogs:/vernemq/logs
      - vernemqetc:/vernemq/etc
    depends_on:
      - database
  
  web:
    build: 
      context: ../../
      dockerfile: ./devops/local/Dockerfile
    restart: always
    container_name: web_app
    ports:
      - 4001:4001
      - 4000:4000
    environment:
      APP_IOT_PORT: ${APP_IOT_PORT}
      APP_API_PORT: ${APP_API_PORT}
      APP_HOSTNAME: ${APP_HOSTNAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SENDGRID_KEY: ${SENDGRID_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      GUARDIAN_API_KEY: ${GUARDIAN_API_KEY}
      GUARDIAN_IOT_KEY: ${GUARDIAN_IOT_KEY}
      ELASTIC_SEARCH_HOST: ${ELASTIC_SEARCH_HOST}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
    depends_on:
      - database
      - es01
      - mqtt_broker
      - redis

volumes: 
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local
  pgdata:
  vernemqdata:
  vernemqlogs:
  vernemqetc:
  redis-data: